person:
  user-name: Jack
  boss: false
  birth: 1982/12/11
  age: 40
  pet:
    name: teddy
    weight: 4.2
  # interests: [football, ACG]
  interests:
    - football
    - ACG
  animals: [cat, dog]
  # score:
  #   English: 80
  #   Math: 90
  scores: { English: 80, Math: 90 }
  salaries:
    - 800
    - 900
  allPets:
    sick:
      - { name: teddy, weight: 4.2 }
      - name: pussy
        weight: 5.2
      - name: kim
        weight: 2.1
    healthy: [{ name: java, weight: 5.6 }, { name: hurry, weight: 6.2 }]
